### PR TITLE
new project: redirects to login if not yet authenticated

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by maxwofford** [comment]
@zachlatta: Could you review and merge this?

**Comment by zachlatta** [comment]
A better approach might be to create a piece of express middleware that checks whether the user is authenticated and redirects to the root page if not. See http://stackoverflow.com/questions/14188834/express-passport-where-is-the-documentation-for-ensureauthentication-isaut for an example of `ensureAuthenticated`.

**Comment by zachlatta** [comment]
ping

**Comment by zachlatta** [comment]
ping

**Comment by maxwofford** [comment]
Just added the ensureAuthenticated() way.

**Pull request merged**
