### PR TITLE
add event dropdown

### PR DESCRIPTION
**Pull request by maxwofford**
_**Not ready for merge yet.**_
- [x] Add event dropdown to form
- [ ] Add backend logic for event dropdown

### CODE REVIEW

**Comment by maxwofford** [comment]
This first commit only adds an event dropdown to the form. I will follow up with the backend logic when there has been some discussion on issue #36 (maybe club should be stored as a tag?).

**Comment by zachlatta** [comment]
Does #36 not being completed block progress on this?

**Comment by maxwofford** [comment]
If we go with storing clubs as a tag in each project file instead of in the folder name, we should probably  change event name to a tag as well.

**Comment by zachlatta** [comment]
Do you think we should continue with the PR with the current data model after the conclusions from our offline chat about this? About waiting until the data model is a blocking issue to change things?

**Comment by maxwofford** [comment]
Yes. I'll add to this PR for keeping events as symbolic links.

**Comment by zachlatta** [comment]
Awesome. I also edited the PR's description to add a checklist of things
that need to be do and a notice that it's ready for merging.

In the future, can you say directly in the description whether or not
it's ready to be merged? Makes it easier when scanning the page, I
almost merged this.

**Comment by maxwofford** [comment]
Events are not currently tracked in hackedu/shipped. Closing this for the time being.

**Pull request closed without merging**
