### PR TITLE
fix issue#1

### LINKED ISSUE #1: It's not clear what the GitHub permissions are needed for
Add a better description of what the utility does on the homepage.

### PR DESCRIPTION
**Pull request by maxwofford**
This closes #1

### CODE REVIEW

**Comment by maxwofford** [comment]
@zachlatta Could I get a second set of eyes on this explanation?

**Comment by zachlatta** [comment]
It might be worth mentioning that this will fork and submit a pull request for you,l. What are your thoughts?

**Comment by zachlatta** [comment]
ping @MaxWofford

**Comment by maxwofford** [comment]
I'm not quite sure I understand what you mean.

**Comment by zachlatta** [comment]
It might be worth mentioning that ship it forks the repository and submits a pull request on your behalf.

**Comment by maxwofford** [comment]
@zachlatta Would you please review this?

**Comment by zachlatta** [comment]
Hmm, I feel like we could simplify this. I'm wary of mentioning things like yaml because it may be intimidating to newcomers.

How about the following?

```
> Ship It is a utility that submits projects to the
> [hackEDU Project Gallery](https://shipped.hackedu.us).
>
> Specifically, it forks the `[shipped](https://github.com/hackedu/shipped)`
> repository and submits a pull request to add a new project for you.
```

**Comment by maxwofford** [comment]
@zachlatta Just rebased and made the change.

**Comment by zachlatta** [comment]
Can you add a more descriptive commit message?

On Fri, Sep 11, 2015 at 10:12 AM, Max Wofford notifications@github.com
wrote:

> @zachlatta https://github.com/zachlatta Just rebased and made the
> change.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/shipit/pull/33#issuecomment-139603895.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Comment by maxwofford** [comment]
@zachlatta Cleaned up the history.

EDIT: Never thought about it before, but it feels so bad-ass to say that. I feel like some time-travelling rogue cop who isn't afraid to break the rules to get results.

>  Cleaning up history. One bullet at a time...
>

**Pull request merged**
