### PR TITLE
new project: form allows multipule clubs per project

### PR DESCRIPTION
**Pull request by maxwofford**
_not ready for merge_

I have a  bug where hovering over the `remove club` button creates an onhover effect on the first club `select` tag. Can someone try replicating this?

@zachlatta Besides the aforementioned issue, this is ready for review.

### CODE REVIEW

**Comment by maxwofford** [comment]
This is not useful unless we refactor the way projects are sorted in folders.

**Comment by maxwofford** [comment]
I will open this when/if https://github.com/hackedu/shipped/pull/83 is merged

**Comment by zachlatta** [comment]
It done been merged.

**Comment by maxwofford** [comment]
@zachlatta This is ready to merge. I've tested it locally by console.loging the generated yml.

**Comment by maxwofford** [comment]
@zachlatta merged from my computer.

**Pull request merged**
