### PR TITLE
new project: club names are in a dropdown

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by zachlatta** [comment]
Hmmm, I'm having trouble seeing the dropdown itself. Here's a screenshot. I see the new placeholder though.

tmp

**Comment by zachlatta** [comment]
Ah, looked into it. I don't run into the same issue with Chrome or Firefox. Is this some sort of new element that's not in the spec? Doesn't seem to be integrated with raw webkit.

What if we did just a plain dropdown?

**Comment by maxwofford** [comment]
Ah, yep. Looks like this isn't supported in Safari. I'll switch it over to a `<select>` tag.

**Comment by zachlatta** [comment]
You can also make the change in this PR and merge the commits into one.

**Comment by maxwofford** [comment]
Oh, I never new that! How can I merge commits in github?

**Comment by zachlatta** [comment]
Check out
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html.
Do that then force push (`git push --force`) to the branch of the PR and
GitHub will update with the merged commits.

You should normally never do this unless it's on your own branch and for
a PR or something.

## 

Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Pull request closed without merging**
