### PR TITLE
Add missing schools

### PR DESCRIPTION
**Pull request by paked**
This is a short term fix for #40

### CODE REVIEW

**Comment by zachlatta** [comment]
For the sake of getting everything in one go, here's a list of all of the clubs, alphabetized.

``` jade
option=(value='Armijo High School') Armijo High School
option=(value='Austin High School') Austin High School
option=(value='Bronx High School of Science') Bronx High School of Science
option=(value='Camino Nuevo High School') Camino Nuevo High School
option=(value='Cherry Hill High School East') Cherry Hill High School East
option=(value='College Park High School') College Park High School
option=(value='Columbia Secondary School') Columbia Secondary School
option=(value='Cranbrook Schools') Cranbrook Schools
option=(value='Crenshaw High School') Crenshaw High School
option=(value='Downey High School') Downey High School
option=(value='Elizabeth High School') Elizabeth High School
option=(value='El Segundo High School') El Segundo High School
option=(value='Garfield Senior High School') Garfield Senior High School
option=(value='Gig Harbor High School') Gig Harbor High School
option=(value='Glenaeon Rudolf Steiner School') Glenaeon Rudolf Steiner School
option=(value='Gunn High School') Gunn High School
option=(value='Hack Camp') Hack Camp
option=(value='HS Hackers/Coded with Kids Meetup') HS Hackers/Coded with Kids Meetup
option=(value='Huntington Park High School') Huntington Park High School
option=(value='International Academy East') International Academy East
option=(value='Linda Márquez High School') Linda Márquez High School
option=(value='Locke High School') Locke High School
option=(value='Los Altos High School') Los Altos High School
option=(value='Lowell High School') Lowell High School
option=(value='Lower Moreland High School') Lower Moreland High School
option=(value='Menlo School') Menlo School
option=(value='Middlesex County Academy') Middlesex County Academy
option=(value='Mission Vista High School') Mission Vista High School
option=(value='Morris County School of Technology') Morris County School of Technology
option=(value='Mundelein High School') Mundelein High School
option=(value='Oscar de la Hoya Ánimo Charter High School') Oscar de la Hoya Ánimo Charter High School
option=(value='Project Cipher') Project Cipher
option=(value='Raleigh Charter High School') Raleigh Charter High School
option=(value='Ravenwood High School') Ravenwood High School
option=(value='Robert F. Kennedy Community Schools') Robert F. Kennedy Community Schools
option=(value='San Francisco University High School') San Francisco University High School
option=(value='San Leandro High School') San Leandro High School
option=(value='San Mateo High School') San Mateo High School
option=(value='Santa Teresa High School') Santa Teresa High School
option=(value='South Brunswick High School') South Brunswick High School
option=(value='The Shri Ram School - DLF Campus') The Shri Ram School - DLF Campus
option=(value='Thunderridge High School') Thunderridge High School
option=(value='Townsend Harris High School') Townsend Harris High School
option=(value='Twin Cities Academy') Twin Cities Academy
option=(value='USC Hybrid High School') USC Hybrid High School
option=(value='West Adams High School') West Adams High School
option=(value='West Orange High School') West Orange High School
```

**Comment by zachlatta** [comment]
(includes Hack Camp)

**Comment by paked** [comment]
@zachlatta rebased and renamed

**Comment by zachlatta** [comment]
Thank you! Merged and deployed.

On Wed, Sep 9, 2015 at 6:16 PM, Harrison Shoebridge <
notifications@github.com> wrote:

> @zachlatta https://github.com/zachlatta rebased and renamed
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/shipit/pull/41#issuecomment-139085891.

## 

Zach Latta
hackEDU | zach@hackedu.us

**Pull request merged**
